# Generated by Django 3.1.1 on 2020-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animar', '0002_auto_20200920_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
