# Generated by Django 3.1.1 on 2020-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animar', '0002_auto_20200918_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
