# Generated by Django 3.1.1 on 2020-09-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animar', '0003_auto_20200921_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
