# Generated by Django 3.1.1 on 2020-09-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animar', '0005_auto_20200923_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='post_images/'),
            preserve_default=False,
        ),
    ]
